---
# Ansible inventory for Kubernetes clusters
# Generated by Terraform from terraform.tfvars

all:
  children:
    control_planes:
      hosts:
%{ for name, cluster in clusters ~}
        ${name}_control_plane:
          ansible_host: ${cluster.controlplane_private_ip}
          cluster_name: ${name}
          pod_network_cidr: "${cluster.pod_cidr}"
%{ endfor ~}
      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: "${ssh_key_path}"
        # Proxy through bastion host
        bastion_host: "${bastion_public_dns}"
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyCommand="ssh -i ${ssh_key_path} -W %h:%p ubuntu@${bastion_public_dns}"'
